### PR TITLE
Models

### PR DESCRIPTION
**Pull request by bridgesMichael**

### CODE REVIEW

**Review by mdubelbeis — APPROVED** [review]
g2g

**Comment by mdubelbeis** [comment]
Confirm merge?

**Comment by leodvincci** [comment]
> Confirm merge?

Just wanted to 

> Confirm merge?

I'm Reviewing Right now...

**Comment by leodvincci** [comment]
Looks Good, No issues jump out to me!
image

**Comment by leodvincci** [comment]
Good To Merge 👍

**Review by leodvincci — APPROVED** [review]

**Pull request merged**
