### PR TITLE
API: created GET request that returns a random question

### PR DESCRIPTION
**Pull request by leodvincci**
-created API to return random question

### CODE REVIEW

**Comment by bridgesMichael** [comment]
When you're getting the single random question, you should just be able to return the single Question object instead of a list(), right? Or does it even matter..

**Comment by leodvincci** [comment]
> ng the single random quest

let me check right quick

**Comment by leodvincci** [comment]
> 

image

**Review by mdubelbeis — APPROVED** [review]
Looks good to my newb eyes

**Pull request closed without merging**
